export const WARNING_SIGNS = [
  {
    id: 'ventilation',
    title: 'Ventilation Failure',
    section: 'always-first' as const,
    script: `Most people assume that roofs fail because of the shingles going bad. And in some cases that may be true. But here in [STATE], the number one reason that we see roofs failing, outside of poor workmanship, is something related to ventilation. The roof system and attic need to breathe — cool air coming in through the soffits, heat and moisture exiting through the ridge vent. Not having proper ventilation leads to excessive heat and moisture being trapped inside the attic space which creates a laundry list of symptoms that destroy roof systems — often from the inside out.`,
    correlatedRoofTags: ['granule-loss', 'curling', 'fish-lip'],
    correlatedAtticTags: ['amber-deposits', 'blocked-soffits', 'inadequate-ridge-vent'],
    stockPhotoQuery: 'roof attic ventilation failure damage',
  },
  {
    id: 'staining',
    title: 'Staining & Discoloration',
    section: 'outside' as const,
    script: `On the outside, the first thing we look for is discoloration. A lot of people mistake this for the roof being dirty or needing a cleaning. But in many cases, this discoloration is actually a visual sign that the shingles are absorbing moisture. You'll see missing granules, exposed fiberglass, vegetation growth — all signs that the shingles are beyond their useful life, are absorbing moisture, and are no longer protecting the home.`,
    correlatedRoofTags: ['staining', 'granule-loss', 'exposed-fiberglass', 'vegetation'],
    correlatedAtticTags: [],
    stockPhotoQuery: 'roof shingle staining discoloration granule loss',
  },
  {
    id: 'curling',
    title: 'Curling Shingles & Nail Pops',
    section: 'outside' as const,
    script: `The next thing we look for are nail pops or shingles that are lifting up. Generally, when we see a lot of nails popping up, it's an indication that the wood decking has become wet and compromised. When the wood is wet, the nails pull out and outside it gives the appearance of curling shingles. The curling can also be due to prolonged exposure to heat. You ever drop a piece of bacon into a frying pan? What happens to the bacon? Yep, it curls up. So on the roof, if the shingles become old, lose their granules, or are made of materials that absorb and retain the sun's heat, they experience what we call thermal shock and will curl, crack, and break.`,
    correlatedRoofTags: ['curling', 'fish-lip', 'nail-pops'],
    correlatedAtticTags: ['dark-wet-decking', 'cat-eyes'],
    stockPhotoQuery: 'curling shingles nail pops roof damage',
  },
  {
    id: 'missing',
    title: 'Missing Shingles',
    section: 'outside' as const,
    script: `You don't need to be a roofing professional to know that missing shingles are a problem, right? That's kind of self explanatory. What we look to do is figure out WHY the shingles are missing so that the new system addresses the root cause, not just the symptoms. Are you with me on that?`,
    correlatedRoofTags: ['missing-shingles', 'damaged-flashing'],
    correlatedAtticTags: ['daylight-decking'],
    stockPhotoQuery: 'missing shingles roof damage exposed decking',
  },
  {
    id: 'water-damage',
    title: 'Water Damage (Attic)',
    section: 'inside' as const,
    script: `In the attic, one of the main things we are going to look for is signs of water damage on the structural wood decking and rafters. When wood is dry and healthy, it's a lighter, almost yellow color. So when we see it dark and discolored, we can tell that water has found its way inside the wood. And as we discussed, that can happen from both the outside OR the inside.`,
    correlatedRoofTags: ['staining', 'missing-shingles', 'damaged-flashing'],
    correlatedAtticTags: ['water-staining-rafters', 'dark-wet-decking', 'mold'],
    stockPhotoQuery: 'attic water damage rafters dark wood moisture',
  },
  {
    id: 'amber',
    title: 'Amber Deposits (Attic)',
    section: 'inside' as const,
    script: `This is something we call ambering. Ambering is a sign that there is excessive heat buildup in the attic space — generally due to a lack of ventilation. When the wood gets extremely hot, the sap inside the wood that holds it together starts to bleed out. Over time there's no more sap left and the wood becomes extremely brittle and cracks. This is extra concerning because typically we see the ambering in structural rafters. Not something you want to have split, right?`,
    correlatedRoofTags: ['granule-loss', 'curling'],
    correlatedAtticTags: ['amber-deposits'],
    stockPhotoQuery: 'attic amber deposits wood rafters heat damage sap',
  },
  {
    id: 'cat-eyes',
    title: 'Cat Eyes (Attic)',
    section: 'inside' as const,
    script: `Finally, we have what we call cat eyes. You see those black ovals on the wood around the nails? If we see those, it's a big red flag that there is a moisture problem in the attic. Condensation forms around the nails and over time begins to rot away the surrounding wood. When the wood is soft and rotten, the nails pull out and you start seeing the curling or fish lip shingles that blow off on the outside.`,
    correlatedRoofTags: ['nail-pops', 'curling', 'fish-lip'],
    correlatedAtticTags: ['cat-eyes'],
    stockPhotoQuery: 'attic cat eyes nail rot condensation wood damage',
  },
  {
    id: 'you-never-know',
    title: 'You Never Really Know',
    section: 'closer' as const,
    script: `This illustrates that roofs can appear fine from the outside while significant structural damage is hidden underneath the shingles. The goal of a professional inspection is to identify these issues before the structural decking becomes extensively damaged. Allowing us to complete the roof and attic inspection is a win-win — you either get validation that the roof is actually in good condition, or you have the opportunity to address small problems before they turn into big ones.`,
    note: 'Use this card when a homeowner is hesitant about attic access or attempts to cancel the inspection. Present Warning Signs BEFORE the inspection in that case.',
    correlatedRoofTags: [],
    correlatedAtticTags: [],
    stockPhotoQuery: 'roof damage hidden under shingles decking comparison',
  },
] as const

export type WarningSectionType = 'always-first' | 'outside' | 'inside' | 'closer'
export type WarningSignId = typeof WARNING_SIGNS[number]['id']
