// Compile the bot-v2 prompt .md tiers into a single bundled TypeScript module.
//
// WHY: the assembler loads prompt content through the `loadPromptTier` seam. At
// runtime under a fully-bundled serverless deploy, the loose .md files may ship
// at neither the module-relative nor the cwd-relative path (bundlers bundle code,
// not markdown read at runtime). Compiling the tiers into an in-memory TS module
// makes them bundle automatically — no runtime disk read — while `loadPromptTier`
// stays the single swappable seam for the future per-tenant CMS.
//
// Tier content is TRIMMED here so the generated constants are byte-identical to
// the old `readFileSync(...).trim()` path — the assembled prompt (and the cache
// prefix that depends on it) does not change.
//
// Run after editing any prompt .md:
//   npm run prompts:compile
// Wired into `prebuild` so `next build` always regenerates before bundling.

import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const PROMPTS_DIR = join(ROOT, "src", "lib", "bot-v2", "prompts");
const OUT_FILE = join(ROOT, "src", "lib", "bot-v2", "prompts.generated.ts");

/** Recursively collect every .md file under dir, returning absolute paths. */
function collectMarkdown(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const abs = join(dir, entry);
    if (statSync(abs).isDirectory()) out.push(...collectMarkdown(abs));
    else if (entry.endsWith(".md")) out.push(abs);
  }
  return out;
}

// tier-path = path relative to the prompts root, no extension, POSIX separators
// (matches the logical keys the assembler passes to loadPromptTier, e.g.
// "kernel/00_identity").
function tierPathFor(abs) {
  return relative(PROMPTS_DIR, abs).replace(/\.md$/, "").split(sep).join("/");
}

const files = collectMarkdown(PROMPTS_DIR).sort();
const entries = files.map((abs) => {
  const tierPath = tierPathFor(abs);
  const content = readFileSync(abs, "utf8").trim();
  return [tierPath, content];
});

const body = entries
  .map(([tierPath, content]) => `  ${JSON.stringify(tierPath)}: ${JSON.stringify(content)},`)
  .join("\n");

const generated = `// AUTO-GENERATED by scripts/compile-prompts.mjs — DO NOT EDIT BY HAND.
// Regenerate after editing any prompt .md:  npm run prompts:compile
//
// Maps each prompt tier-path to its TRIMMED .md content. Bundled into the build
// so the assembler resolves all tiers in-memory with no runtime disk read.
// ${entries.length} tiers compiled.

export const PROMPT_TIERS: Record<string, string> = {
${body}
};
`;

writeFileSync(OUT_FILE, generated, "utf8");
console.log(`[compile-prompts] wrote ${entries.length} tiers → ${relative(ROOT, OUT_FILE)}`);
